### ISSUE TITLE
SOAPクライアントに対するタイムアウト設定の記載内容の変更

### ISSUE THREAD

**Issue by bttsuchiyahrh** [terasolunaorg/guideline#2775]
## Description
「SOAP Web Service」ページのクライアントのタイムアウト設定の記載内容を変更する。
"com.sun.xml.internal.ws.connect.timeout"と、"com.sun.xml.internal.ws.request.timeout"プロパティに対して、value-type属性でInteger型を指定する記載内容となっているが、value-type属性で明示的にInteger型を指定するのは違和感があるためvalue-type属性の指定を削除する。

補足
value-type属性の指定がない場合は、String型が適用される。

【背景】
value-type属性の記載がない場合は、String型が適用される。
現在の記載が、value-typeまで含めた内容となっているのは、weblogicが明示的にInteger型を指定しないとエラーになることが判明したために、後にvalue-typeごと記載を追記したためである。
ただし、後に、WAS Traditionalの動作確認を実施したところ、Integer型の指定があるとエラーになる(String型が正しい指定)ことが判明した。
また、weblogicとWAS Traditional以外の実行環境では、String,Integerのどちらでも正常に動作する。
上記の点を考慮して、weblogicが特異な例と判断し、weblogicだけNOTEで記載するように変更する。

## Possible Solutions
「SOAP Web Service」ページの「5.3.2.2.5. タイムアウトの設定」に記載のある、
タイムアウト設定の記載内容を変更する。
具体的には、bean id="todoWebService"の記載内容を下記のように変更する。

変更前
key="com.sun.xml.internal.ws.connect.timeout" value-type="java.lang.Integer" ...
key="com.sun.xml.internal.ws.request.timeout" value-type="java.lang.Integer" ...
変更後
key="com.sun.xml.internal.ws.connect.timeout" ...
key="com.sun.xml.internal.ws.request.timeout" ...

また、weblogicの場合だけは、value-typeを含めた変更前の指定内容にする必要があるという旨のNOTEを追記する。

## Affects Version/s
* 5.3.1.RELEASE
* 5.4.0.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1

## Issue Links
* #XXX

## ChangeLog
not required (improvement)

## Translation
- [ ] required

**Comment by yoshikawaa** [comment]
@bttsuchiyahrh 
Thanks!

@itouyun 
Please write issue for translation, and close this.
And I tried to add `Translation` section in issue description. How do you like it?

**Comment by itouyun** [comment]
@yoshikawaa 
I made translation issue.
Thank you for your opinion. This is good idea. I will fix issue template inside `Translation` section.

**Comment by kazuki43zoo** [comment]
@yoshikawaa @bttsuchiyahrh @itouyun 

> WebLogicで該当キーを指定する場合は、value-type 属性でInteger型を指定する必要がある。

という説明になっておりWebLogic以外では型の指定は不要と読み取れますが、実はこの説明は正しくなさそうです。

Tomcat上でClientとServerを別のWebアプリとしてデプロイし、CXFをServer側だけに組み込んだ状態で動かした場合にも同様のエラーが発生しました。

```
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.createHttpConnection(HttpClientTransport.java:272)
	at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:101)
	... 135 common frames omitted
```

おそらく・・・JDK内包のJAX-WS実装( or ←をベースにした実装)の場合に同様の事象が発生するのだと思われるので、再調査を行いガイドラインに反映してほしいです。

**Comment by itouyun** [comment]
@kazuki43zoo 
今回の修正は、issueの背景に記載されている
> weblogicが特異な例と判断し、weblogicだけNOTEで記載する

を正として修正が施されましたが、特異な例はWebLogicのみに依存するわけではない、というわけですね。
再調査をして特異な例を詳細化したのち、ガイドライン上はWebLogicの場合のみのNOTEと思われないような文章（"例えばWebLogicのように"的な文は残してもよさそう）に変更する感じですかね。

**Comment by itouyun** [comment]
ClientとServerを別のWebアプリとしてデプロイした環境で諸々の再調査を行ってから本issueにおけるガイドライン修正を実施する。
